### PR TITLE
Support excluding all dependencies in pom

### PR DESCRIPTION
**Pull request by jtgrabowski**
The idea here is that when exclude contains wildcards for
organisation and name than the dependency is inTransitive.

This:

```
<dependency>
    <groupId>x</groupId>
    <artifactId>y</artifactId>
    <version>z</version>
    <exclusions>
        <exclusion>
            <artifactId>*</artifactId>
            <groupId>*</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

Before change was translated to:

```
<dependency org="x" name="y" rev="z" force="true" transitive="true"
conf="compile->compile(*),master(compile);runtime->runtime(*)">
    <exclude org="*" module="*" name="*" type="*" ext="*" conf=""
matcher="exact"/>
</dependency>
```

And now it is translated to:

```
<dependency org="x" name="y" rev="z" force="true" transitive="false"
conf="compile->compile(*),master(compile);runtime->runtime(*)"/>
```

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jtgrabowski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by dwijnand** [comment]
LGTM

**Comment by eed3si9n** [comment]
Awesome

**Comment by dwijnand** [comment]
@jtgrabowski I ran a local publish of this with your test in https://github.com/sbt/sbt/pull/2713, and it worked!

Excellent job and thank you for contributing. Merging.

**Pull request merged**
