### PR TITLE
SBT Update performance downgrade caused by large number of dependencyOve...

### PR DESCRIPTION
**Pull request by Kewpie007**
...rrides

In order to keep artifact version standards following the train, we need to use SBT dependencyOverrides.
The overrides include about 950 entries long. Once we put the overrides into play, the udpate time goes
up by 4x-5x. With profiler data, we identify a severe hot spot at ModuleRules.getRules(), which consumes

> 80% CPU and >900MB memmory usage in our case. The root cuase is ivy has to iterate whole rule map to
> to find right matchers, so the performance is downgraded significantly when rules map is pretty large.
> This patch target to speed up matcher lookup for dependencyOverrides resolution.

The issue was initially raised at 

  http://stackoverflow.com/questions/22187264/dependencyoverrides-causes-sbt-update-times-to-go-up-by-4-5x

From our test, we observe 60% SBT Update time improvement with this change.

### CODE REVIEW

**Comment by Kewpie007** [comment]
I did sign the CLA.

**Comment by jsuereth** [comment]
Great! I'm creating a 2.4.x-sbt branch where I think we'll merge this into, as well as other 2.4.x sbt fixes that we'll track against master.

**Comment by jsuereth** [comment]
K, thanks for the fix.  Merged into a 2.4.x-sbt branch. I'll be making that the default for this repo.

**Comment by jsuereth** [comment]
Also, 50% Update time improvement confirmed on my end.

**Pull request closed without merging**
